directors/urls.py
from django.urls import path

from . import views

app_name = "directors"

urlpatterns = [
    path("", views.DirectorListView.as_view(), name="list"),
    path("create", views.DirectorCreateView.as_view(), name="create"),
    path(
        "<str:pk>/update",
        views.DirectorUpdateView.as_view(),
        name="update",
    ),
    path(
        "<str:pk>/delete",
        views.DirectorDeleteView.as_view(),
        name="delete",
    ),
]

movies/urls.py
from django.urls import path

from . import views

app_name = "movies"

urlpatterns = [
    path("", views.MovieListView.as_view(), name="list"),
    path("create", views.MovieCreateView.as_view(), name="create"),
    path(
        "<slug:slug>/update",
        views.MovieUpdateView.as_view(),
        name="update",
    ),
    path(
        "<slug:slug>/delete",
        views.MovieDeleteView.as_view(),
        name="delete",
    ),
    path(
        "<slug:slug>/detail",
        views.MovieDetailView.as_view(),
        name="detail",
    ),
]

movies_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("studios/", include("studios.urls")),
    path("movies/", include("movies.urls")),
    path("directors/", include("directors.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studios/urls.py
from django.urls import path

from . import views

app_name = "studios"

urlpatterns = [
    path("create", views.StudioCreateView.as_view(), name="create"),
    path("", views.StudioListView.as_view(), name="list"),
    path(
        "<slug:slug>/update",
        views.StudioUpdateView.as_view(),
        name="update",
    ),
    path(
        "<slug:slug>/delete",
        views.StudioDeleteView.as_view(),
        name="delete",
    ),
]

directors/models.py
from django.db import models

directors/forms.py
from django import forms
from django.forms import widgets

from studios.models import *


class DirectorCreateForm(forms.ModelForm):
    class Meta:
        model = Director
        fields = [
            "first_name",
            "middle_name",
            "last_name",
            "phone_number",
            "birthdate",
            "gender",
            "website",
        ]

directors/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib import messages


from studios.models import Director
from .forms import DirectorCreateForm


class DirectorListView(ListView):
    model = Director
    paginate_by = 6
    context_object_name = "directors"
    template_name = "directors/director_list.html"


class DirectorCreateView(CreateView):
    form_class = DirectorCreateForm
    template_name = "directors/create_director.html"
    success_url = reverse_lazy("directors:list")


class DirectorUpdateView(UpdateView):
    model = Director
    form_class = DirectorCreateForm
    template_name = "directors/create_director.html"
    success_url = reverse_lazy("directors:list")


class DirectorDeleteView(DeleteView):
    model = Director
    template_name = "directors/delete_director.html"
    context_object_name = "director"

    def get_success_url(self):
        messages.success(self.request, "Director Profile was deleted successfully.")
        return reverse("directors:list")

directors/templates/base_director.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body class = "bg-gray-100">
        <div class = "bg-red-800 grid grid-flow-col justify-items-start space-x-3">
            <div class = " w-2/3 ">
                <h2 class="p-4 font-bold font-sans text-4xl text-white">
                    Directors
                </h2>
            </div>
            <div class = "flex w-full justify-end space-x-3">
                <a class="p-6 font-bold text-white object-left " href= "{% url 'directors:create'%}">Create Director</a>
                <a class="p-6 font-bold text-white object-left" href= "{% url 'directors:list'%}">All Directors</a>
                <a class="p-6 font-bold text-white object-left" href= "{% url 'movies:list'%}">All Movies</a>
                <a class="p-6 font-bold text-white object-left" href= "{% url 'studios:list'%}">All Studios</a>
            </div>
          </div>
        <div class = "container mx-auto" >
        {% block content %}
        {% endblock content %}
        </div>

    </body>
</html>