directors/urls.py
from django.urls import path

from . import views

app_name = "directors"

urlpatterns = [
    path("", views.DirectorListView.as_view(), name="list"),
    path("create", views.DirectorCreateView.as_view(), name="create"),
    path(
        "<str:pk>/update",
        views.DirectorUpdateView.as_view(),
        name="update",
    ),
    path(
        "<str:pk>/delete",
        views.DirectorDeleteView.as_view(),
        name="delete",
    ),
]

movies/urls.py
from django.urls import path

from . import views

app_name = "movies"

urlpatterns = [
    path("", views.MovieListView.as_view(), name="list"),
    path("create", views.MovieCreateView.as_view(), name="create"),
    path(
        "<slug:slug>/update",
        views.MovieUpdateView.as_view(),
        name="update",
    ),
    path(
        "<slug:slug>/delete",
        views.MovieDeleteView.as_view(),
        name="delete",
    ),
    path(
        "<slug:slug>/detail",
        views.MovieDetailView.as_view(),
        name="detail",
    ),
]

movies_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("studios/", include("studios.urls")),
    path("movies/", include("movies.urls")),
    path("directors/", include("directors.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studios/urls.py
from django.urls import path

from . import views

app_name = "studios"

urlpatterns = [
    path("create", views.StudioCreateView.as_view(), name="create"),
    path("", views.StudioListView.as_view(), name="list"),
    path(
        "<slug:slug>/update",
        views.StudioUpdateView.as_view(),
        name="update",
    ),
    path(
        "<slug:slug>/delete",
        views.StudioDeleteView.as_view(),
        name="delete",
    ),
]

movies/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from taggit.managers import TaggableManager
from django.utils.text import slugify


from phonenumber_field.modelfields import PhoneNumberField


class Studio(models.Model):
    title = models.CharField(max_length=40, unique=True)
    website = models.URLField(max_length=400)
    slug = models.SlugField(max_length=200)

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Director(models.Model):
    GENDER_CHOICES = (("M", "Male"), ("F", "Female"), ("O", "Others"))
    first_name = models.CharField(max_length=40)
    middle_name = models.CharField(max_length=40, blank=True)
    last_name = models.CharField(max_length=40)
    phone_number = PhoneNumberField(unique=True, blank=True)
    birthdate = models.DateField(auto_now=False, auto_now_add=False)
    website = models.URLField(max_length=400)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    def save(self, *args, **kwargs):
        value = self.first_name + self.last_name
        self.slug = slugify(value)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.first_name + self.last_name


class Movies(models.Model):
    title = title = models.CharField(max_length=40, unique=True)
    subtitle = models.URLField(max_length=400)
    slug = models.SlugField(max_length=200)
    directors = models.ManyToManyField(Director)
    studio = models.ForeignKey(Studio, on_delete=CASCADE)
    released_date = models.DateField(auto_now=False, auto_now_add=False)
    cover_image = models.ImageField(upload_to="images", null=True, blank=True)
    review = models.TextField(max_length=1000)
    genre = TaggableManager(blank=True)
    asin = models.IntegerField(unique=True)

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

movies/forms.py
from django import forms
from django.forms import widgets

from studios.models import *


class MovieCreateForm(forms.ModelForm):
    class Meta:
        model = Movies
        fields = [
            "title",
            "subtitle",
            "directors",
            "studio",
            "released_date",
            "cover_image",
            "review",
            "genre",
            "asin",
        ]
        widgets = {
            "review": forms.Textarea(attrs={"rows": 4, "cols": 15}),
            "released_date": forms.DateInput(
                attrs={
                    "class": "datepicker",
                    "placeholder": "Select a date",
                    "type": "date",
                }
            ),
        }

movies/views.py
from django.db import models
from django.shortcuts import render
from django_filters.views import FilterView

from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
    DetailView,
)
from django.urls import reverse_lazy, reverse
from django.contrib import messages


from studios.models import Movies
from .forms import MovieCreateForm
from .filters import MovieFilter


class MovieListView(FilterView):
    model = Movies
    filterset_class = MovieFilter
    paginate_by = 6
    context_object_name = "movies"
    template_name = "movies/movie_list.html"


class MovieCreateView(CreateView):
    form_class = MovieCreateForm
    template_name = "movies/create_movie.html"
    success_url = reverse_lazy("movies:list")


class MovieUpdateView(UpdateView):
    model = Movies
    form_class = MovieCreateForm
    template_name = "movies/create_movie.html"
    success_url = reverse_lazy("movies:list")


class MovieDeleteView(DeleteView):
    model = Movies
    template_name = "movies/delete_movie.html"
    context_object_name = "movie"

    def get_success_url(self):
        messages.success(self.request, "movie was deleted successfully.")
        return reverse("movies:list")


class MovieDetailView(DetailView):
    model = Movies
    template_name = "movies/detail_view.html"
    context_object_name = "movie"

movies/templates/base_director.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body class = "bg-gray-100">
        <div class = "bg-red-800 grid grid-flow-col justify-items-start space-x-3">
            <div class = " w-2/3 ">
                <h2 class="p-4 font-bold font-sans text-4xl text-white">
                    Directors
                </h2>
            </div>
            <div class = "flex w-full justify-end space-x-3">
                <a class="p-6 font-bold text-white object-left " href= "{% url 'create_director'%}">Create Director</a>
                <a class="p-6 font-bold text-white object-left" href= "{% url 'list_director'%}">All Directors</a>
            </div>
          </div>
        <div class = "container mx-auto" >
        {% block content %}
        {% endblock content %}
        </div>

    </body>
</html>

movies/templates/base_movie.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body class = "bg-gray-100">
        <div class = "bg-green-800 grid grid-flow-col justify-items-start space-x-3">
            <div class = " w-2/3 ">
                <h2 class="p-4 font-bold font-sans text-4xl text-white">
                Movies
                </h2>
            </div>
            <div class = "flex w-full justify-end space-x-3">
                <a class="p-6 font-bold text-white object-left " href= "{% url 'movies:create'%}">Create Movie</a>
                <a class="p-6 font-bold text-white object-left" href= "{% url 'movies:list'%}">All Movies</a>
                <a class="p-6 font-bold text-white object-left" href= "{% url 'directors:list'%}">All directors</a>
                <a class="p-6 font-bold text-white object-left" href= "{% url 'studios:list' %}">All studios</a>
            </div>
          </div>
        <div class = "container mx-auto" >
        {% block content %}
        {% endblock content %}
        </div>

    </body>
</html>

movies/templates/base_studio.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body class = "bg-gray-100">
        <div class = "bg-blue-800 grid grid-flow-col justify-items-start space-x-3">
            <div class = " w-2/3 ">
                <h2 class="p-4 font-bold font-sans text-4xl text-white">
                Studios
                </h2>
            </div>
            <div class = "flex w-full justify-end space-x-3">
                <a class="p-6 font-bold text-white object-left " href= "{% url 'create_studio'%}">Create Studio</a>
                <a class="p-6 font-bold text-white object-left" href= "{% url 'list_studio'%}">All studios</a>
            </div>
          </div>
        <div class = "container mx-auto" >
        {% block content %}
        {% endblock content %}
        </div>

    </body>
</html>